### ISSUE TITLE
Appveyor fails

### ISSUE THREAD

**Issue by opoudjis** [metanorma/html2doc#19]
On installing puppeteer from node

**Comment by CAMOBAP795** [comment]
@opoudjis actually it's not related to 

```
npm.cmd : 
At line:3 char:1
+ & npm i -g puppeteer
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

For all failed test cases issue the same difference in output:
```
-Content-Type: application/xml
+Content-Type: text/xml charset="utf-8"
```

Looking for solution

**Comment by CAMOBAP795** [comment]
Update

 [`MIME::Types.type_for(item)`](https://github.com/mime-types/ruby-mime-types/blob/master/lib/mime/types.rb#L151) looks unstable across platforms

**Comment by opoudjis** [comment]
Passes now, have fixed rspec to allow for different CR between Windows and Unix in HTML header.
