### ISSUE TITLE
Add Windows image inclusion test for `html2doc` to ensure Base64'ed image is same as original image

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/html2doc#26]
From https://github.com/metanorma/html2doc/pull/25

The point is to add a test to ensure the original image is Base64 encoded correctly in the output.

For @camobap795

**Comment by CAMOBAP795** [comment]
The only way I see here is to add `rmagick` for image validation

@ronaldtse let me know if you have different idea

**Comment by ronaldtse** [comment]
The validation can just extract the Base64 into an image file, and compare if the input image file and extracted output image file are the same (it should be bit-by-bit equal).

**Comment by CAMOBAP795** [comment]
On it, I worried about the fact that generated images will be deleted at assert time but looks like there is debug mode for this

**Comment by CAMOBAP795** [comment]
@ronaldtse could you please check PR https://github.com/metanorma/html2doc/issues/28

**Comment by CAMOBAP795** [comment]
Merged, closed
