### ISSUE TITLE
Error Bootsnap::LoadPathCache::FallbackScan on Rails 5

### ISSUE THREAD

**Issue by nmenag** [metanorma/html2doc#42]
I am trying use the gem with Rails 5.2.6.2 but return this error: 

`Error Bootsnap::LoadPathCache::FallbackScan on Rails 5`

My app is a Rails API  and I am using the latest version.

**Comment by nmenag** [comment]
it is my error, I am try to do a require of package does not exist.

**Comment by opoudjis** [comment]
OK. In future, @nmenag, feel free to assign issues direct to me; but note that  per #43, we won't support LibreOffice directly in our format...

**Comment by nmenag** [comment]
@opoudjis thanks, I was using htmltoword but I have had many issues so I was looking for a good implementation and this gem is amazing, great job.
