### ISSUE TITLE
Specifying image sizes, image size by percentage

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/html2doc#44]
Images currently are blown up to full document width if their native dimensions are beyond 680x400 (w x h).

This breaks in a table where there are multiple images, and requires manual remediation.

Yet there is a bug here:
* if the user only specifies width or height, the images are still blown up to max, if one of the original dimensions exceed 680x400 (it should be compared to the "post-processing" dimensions, not the original dimensions)
* the user must specify both width AND height for the behavior to take place
  * however, it is difficult for user to manually calculate width and height according to the correct aspect ratio.

Resolutions:
* Provide a "%" option to shrink size
* If user has specified any of width or height, html2doc should help user calculate the other width/height according to aspect ratio

```adoc
[cols="2a,a,2a"]
|===

|
image::figure1.png[width=100,height=50] <=== works, but difficult for user
|
image::figure2.png[width=100] <=== doesn't work
|
image::figure3.png[height=100] <=== doesn't work

|===
```

**Comment by opoudjis** [comment]
Word documents have done:

````
if node["height"] == "auto" || node["width"] == "auto"
        attrs[:height] = nil
        attrs[:width] = nil
      end
````

This means that if only one size parameter of the image is specified, neither is making it to Word, and the document is being resized to full size. That behaviour needs to be suppressed.

This code dates from https://github.com/metanorma/metanorma-rsd/issues/12#issuecomment-404089492 . I was right that Word would not understand `height="auto"`, but the recalculation of the image size that takes place via Html2Doc if height=0 means it does not need to anyway.

**Comment by opoudjis** [comment]
> Provide a "%" option to shrink size

Thought you'd just casually sneak a major feature addition in to an urgent bugfix ticket, did you?

No, this will not get actioned now. Demoted to medium priority.

**Comment by opoudjis** [comment]
Percentage will be recognised, and converted on preprocessing to pixel value. @alexeymorozov This doesn't affect you, right?

**Comment by opoudjis** [comment]
@alexeymorozov I'm moving  image_resize(img, path, maxheight, maxwidth) and  get_image_size(img, path) from html2doc to metanorma-utils anyway

**Comment by opoudjis** [comment]
Still working on this in isodoc...

**Comment by alexeymorozov** [comment]
> @alexeymorozov I'm moving image_resize(img, path, maxheight, maxwidth) and get_image_size(img, path) from html2doc to metanorma-utils anyway

👍 The work doesn't intersect with vectory integration except of 1 line.

**Comment by alexeymorozov** [comment]
@opoudjis Would you like the `image_resize` methods also to be moved to `vectory`?

**Comment by ronaldtse** [comment]
@alexeymorozov that’s probably a good idea. Any vector image manipulation or attribute reading should be in vectory.

**Comment by opoudjis** [comment]
They are nothing to do with vectors, they apply to images generically. OTOH, you did move DataURI functionality to vectory as well, and that too is generic functionality. Don't care one way or the other...

**Comment by ronaldtse** [comment]
We might just extend Vectory to handle raster images as well...
