### ISSUE TITLE
Support nokogiri 1.11

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/html2doc#55]
From @eneagoe in https://github.com/metanorma/html2doc/commit/8b526eb1714d624771ce095e4e96e6dac47f17de#r48091634:

> Could this be relaxed to permit nokogiri 1.11?

**Comment by opoudjis** [comment]
No: https://github.com/metanorma/packed-mn/issues/76

So long as we require Ruby 2.4 to build packed-mn, we cannot upgrade to Nokogiri 1.11.

**Comment by ronaldtse** [comment]
@opoudjis why don't we lock the html2doc version in packed-mn instead?

**Comment by opoudjis** [comment]
I know nothing about packed-mn. Could you put me in touch with the maintainer?

**Comment by ronaldtse** [comment]
The maintainers are @CAMOBAP ane @w00lf

**Comment by opoudjis** [comment]
@CAMOBAP and @w00lf, does it even make sense to freeze html2doc (and the other gems using nokogiri) to 1.10, and upgrade nokogiri to 1.11 for "live" metanorma? Because if packed-mn is meant to be a binary of metanorma, that means it is frozen to a previous version, no?

**Comment by CAMOBAP** [comment]
@opoudjis @w00lf  I propose to use `~> 1.10` This means that it will be resolved to `1.10.10` for rubies 2.4, 2.5, 2.6, 2.7 and `1.11` or above for 2.5, 2.6, 2.7, 3.0

So I propose to leave it up to bundler

**Comment by ronaldtse** [comment]
Agree with @CAMOBAP , he’s already shown this to be the case with another gem that fontist depends on.

**Comment by eneagoe** [comment]
Can the `wontfix` be reconsidered? It looks like there are solutions for both supporting `ruby 2.4` and `nokogiri 1.11`

**Comment by ronaldtse** [comment]
Thanks @eneagoe -- @CAMOBAP could you have a look if we can permit this? Thanks!

**Comment by eneagoe** [comment]
Thank you! This can probably be closed, the latest version (`1.1.2`) supports `nokogiri 1.11`.

**Comment by opoudjis** [comment]
Thank you for your patience,  @eneagoe !

**Comment by opoudjis** [comment]
And FWIW, we have finally removed the packed-mn dependency on Ruby 2.4, so Metanorma henceforth has minimum Ruby version 2.5.
