### ISSUE TITLE
Insufficient permissions for gem release

### ISSUE THREAD

**Issue by opoudjis** [metanorma/html2doc#76]
https://github.com/metanorma/html2doc/actions/runs/3384704471

This is on critical path to release (Monday 7 Nov)

**Comment by CAMOBAP** [comment]
Just to be on the same page, gem release happens successfully. This is a general part for notification  of other repos

I will double check it anyway, but it's definitely not critical for upcoming release

**Comment by opoudjis** [comment]
Right, I realized that afterwards. The error is spurious, but you're right that it's not a blocker

**Comment by CAMOBAP** [comment]
@ronaldtse could you please doublecheck token, because other parts looks correct

**Comment by ronaldtse** [comment]
> @ronaldtse could you please doublecheck token, because other parts looks correct

The tokens are correct. 

![Uploading Screen Shot 2022-11-10 at 4.14.44 PM.png…]()

**Comment by ronaldtse** [comment]
> @ronaldtse could you please doublecheck token, because other parts looks correct

I've finally fixed this -- the CI user did not have access to this repo earlier.
