### ISSUE TITLE
tests-passed failing

### ISSUE THREAD

**Issue by opoudjis** [metanorma/html2doc#78]
May be because I've just switched to main branch for releases? repo is already defaulting to main.

https://github.com/metanorma/html2doc/actions/runs/4654138418/jobs/8235815181

**Comment by CAMOBAP** [comment]
We have the same issue before https://github.com/metanorma/html2doc/issues/76

@ronaldtse could you please:
1. confirm that `METANORMA_CI_PAT_TOKEN` is not defined in this repo?
2. I remember that previously we faced such cases when organization-level tokens were "invisible" for particular repos. IDK which rules apply there for visibility of the token may I ask you to doublecheck the list of repos where our secrets are available like described here https://docs.github.com/en/codespaces/managing-codespaces-for-your-organization/managing-encrypted-secrets-for-your-repository-and-organization-for-github-codespaces#adding-secrets-for-an-organization

**Comment by ronaldtse** [comment]
1. The token is defined but the user did not have write access to this repo. This is now fixed.
2. Private repos do not automatically have access to GHA tokens, they need to be manually added to private repos individually.

**Comment by CAMOBAP** [comment]
Thanks, confirmed https://github.com/metanorma/html2doc/actions/runs/4654643974
